"""Phase 1 decisions (first filing pass).  Judgments only: rule-derived flags
(hold, post-closing, ethical-wall, restricted, duplicate-retained), privilege and
paths are computed by build_filing.py from matters.csv / staff.csv and the rules.

Fields per email id (file name without .eml):
  cat   matter | needs_review | firm_admin | non_matter   (duplicates are detected by Message-ID)
  m     primary matter number (matter emails only)
  x     cross-reference matters (same client only)
  f     manual flags: potential-conflict new-matter-request misdirected phishing
        delivery-failure attorney-action
  priv  optional privilege override
  sum   one-line body summary
  att   {attachment filename: what it shows}
  why   category / matter reasoning and judgment calls
"""

# client contacts worked out from sender domains and content (client contacts are not listed in the CSVs)
CLIENT_PEOPLE = {
    '1001': ['brightwaterfoods.test'],
    '1002': ['mdelgado.home@mailbox.test'],
    '1003': ['northpointlogistics.test'],
    '1004': ['callowaymed.test'],
    '1005': ['paul.ostrander@mailbox.test'],
    '1006': ['fenwicklanehoa.test'],
    '1007': ['blueheronmarina.test'],
    '1008': ['satoarch.test'],
}

D = {
'AAMk017ff12229': dict(cat='matter', m='1008-001', f=[],
  sum='Mira asks Tom to draft a demand letter to Rivera & Sons; position is no payment for work not performed.',
  why='Sato Architecture / Rivera & Sons Roofing fee dispute (1008-001). Internal attorney-to-paralegal message, so work product.'),
'AAMk03552454f1': dict(cat='matter', m='1001-001', f=[],
  sum="Kestrel's counsel serves second document production volume.",
  att={'production_vol2_index.pdf': 'Text PDF: "Kestrel Packaging Ltd - Document Production Volume 2, Index KPL004001-KPL006250".'},
  why='Opposing counsel (Tolland Law) in Brightwater v. Kestrel; Kestrel production index confirms 1001-001. Third party, so no privilege. Dated after hold start.'),
'AAMk04f542441d': dict(cat='matter', m='1003-001', f=[],
  sum='Northpoint reports management approved settlement authority for the Tran mediation.',
  why='Tran employment claim (1003-001) is named in the subject; client contact Hank Moreau (northpointlogistics.test). Anika Brandt is not on the email, so no wall incident. Tom Weller is not screened.'),
'AAMk0749fe85b0': dict(cat='matter', m='1008-001', f=[],
  sum='Sato asks whether mediation makes sense before going further with Rivera.',
  why='Rivera roofing fee dispute (1008-001); client contact Kenji Sato (satoarch.test).'),
'AAMk090f3ebdd3': dict(cat='matter', m='1005-001', f=['potential-conflict', 'new-matter-request'],
  sum="Paul Ostrander approves the kids' holiday schedule, then asks whether Ravi can help his brother with a slip contract at Blue Heron Marina.",
  why='Mainly the Ostrander divorce (1005-001, filed first), so rule 2 applies: file in the existing matter and add new-matter-request (services for the brother). Blue Heron Marina is a current client (1007-001), and a prospective slip holder is on the other side of a marina slip contract, so I also flagged potential-conflict. No stub in the Blue Heron folders (different client). Ravi and the ethics partner must decide.'),
'AAMk0de90794df': dict(cat='matter', m='1001-002', f=[],
  sum='Dana sends photos "as discussed" with no description in the body.',
  att={'IMG_2211.pdf': 'IMAGE-ONLY SCAN (upright). Heading "Specimen of use", "Mark: SUNHARVEST", "Retail packaging label - front panel".'},
  why='Body is empty of substance; the scan shows a SunHarvest specimen of use, so it belongs to the SunHarvest trademark application (1001-002) handled by Leah Park (the addressee). Not the Kestrel dispute despite the same client.'),
'AAMk108743feb6': dict(cat='firm_admin',
  sum='Automated Box notice that the firm storage is 91% full.',
  why='Firm storage notice to the front-desk mailbox: firm business.'),
'AAMk1162f28d1a': dict(cat='matter', m='1001-001', f=[],
  sum='Mira gives Dana and Jonah her recommendation on Kestrel settlement feeler (privileged).',
  why='Brightwater v. Kestrel (1001-001); only firm staff and client take part, so attorney-client. Under hold. Jonah is staff (matter 1001-003 responsible attorney), not a third party.'),
'AAMk15a9964aef': dict(cat='matter', m='1007-001', f=[],
  sum='Sam Pryce sends the insurance certificate Jonah requested.',
  att={'coi.pdf': 'IMAGE-ONLY SCAN, rotated 90 degrees. "CERTIFICATE OF LIABILITY INSURANCE", "Certificate holder: Blue Heron Marina LLC", "Re: Slip C lease".'},
  why='The email has no matter reference; the rotated scan names Blue Heron Marina LLC and the Slip C lease, so 1007-001. Overlapping name: "Heron" is also Project Heron (1004-002); sender domain blueheronmarina.test and the scan settle it.'),
'AAMk15d7185dda': dict(cat='matter', m='1001-001', f=[],
  sum='Dana sends the April Kestrel emails as one PDF.',
  att={'april_emails.pdf': 'Text PDF: "Export: Brightwater purchasing mailbox - Correspondence with Kestrel Packaging Ltd, April 2026".'},
  why='Kestrel dispute evidence (1001-001); under hold. Client-attorney communication.'),
'AAMk1b66809a11': dict(cat='needs_review', f=['new-matter-request'],
  sum='Sam Pryce reports a visiting boat struck the fuel dock, the boat owner\'s insurer has called, and asks Jonah to advise on the damage claim.',
  why='Blue Heron Marina is client 1007, but its only matter is the Slip C lease. A damage claim after a fuel-dock collision is a new request for services outside every existing matter, so it cannot be filed in 1007-001. Subject says "Heron" but it is Blue Heron Marina, not Project Heron (Calloway). Not filed by keyword.',
  nr=('New request for legal services (fuel dock damage claim) outside matter 1007-001; no matter exists. Needs a conflict check and engagement decision, since the boat owner\'s insurer is involved.',
      'Whether to open a new matter for Blue Heron Marina and run a conflict check on the visiting boat owner and insurer.',
      'Jonah Hartwell (responsible attorney for Blue Heron Marina and ethics partner)')),
'AAMk1bc42b7170': dict(cat='matter', m='1004-002', f=[],
  sum='Elena Varga sends draft escrow instructions for the Heron acquisition.',
  att={'escrow_instructions.pdf': 'Text PDF: "ESCROW INSTRUCTIONS - DRAFT; Buyer: Calloway Medical Group PC; Seller: Riverside Imaging LLC".'},
  why='Project Heron = Calloway acquisition of Riverside Imaging (1004-002), confirmed by the attachment. Not Blue Heron Marina. Not restricted (only 1004-001 is).'),
'AAMk244dabb481': dict(cat='matter', m='1008-001', f=[],
  sum='Sato asks how to respond to Rivera & Sons billing for uncompleted roof work at 210 Mill Street.',
  why='1008-001 Rivera Roofing Dispute, matches matter name and address.'),
'AAMk2fcb008853': dict(cat='matter', m='1004-002', f=[],
  sum="Elena Varga sends Riverside's responses to the diligence request list.",
  att={'diligence_responses.pdf': 'Text PDF: "Riverside Imaging LLC - Responses to Due Diligence Request List, prepared for Calloway Medical Group PC".'},
  why='Project Heron acquisition (1004-002), Riverside Imaging named in the attachment.'),
'AAMk30965eda32': dict(cat='matter', m='1003-002', f=[],
  sum='Northpoint forwards the landlord counter-proposal for Dock 7 (4% annual escalator).',
  att={'landlord_letter.pdf': 'IMAGE-ONLY SCAN, upside down (rotated 180). "HARBORVIEW PROPERTIES - Re: Dock 7 - lease renewal - Counter-proposal: 5-year term, 4% annual escalator - Tenant: Northpoint Logistics LLC".'},
  why='Dock 7 lease renewal (1003-002); scan read after rotating it.'),
'AAMk32a123f501': dict(cat='matter', m='1004-002', f=[],
  sum='Jonah congratulates Elena on board approval and sends the closing checklist.',
  why='Project Heron acquisition (1004-002); board vote on Heron matches the 08-17 and 09-02 context. Attorney to client, privileged.'),
'AAMk32d7a94ded': dict(cat='matter', m='1001-001', f=[],
  sum="Kestrel's counsel says they intend to depose Dana Whitcomb in late September and asks Mira for dates.",
  why='Kestrel dispute. Original of a duplicate pair (same Message-ID as AAMk9770c6a5b8, identical Date); the file with the lower name is treated as the earlier one. Under hold. Opposing counsel, no privilege.'),
'AAMk360023b682': dict(cat='matter', m='1002-001', f=[],
  sum='Maria Delgado sends a scan with the subject "scan0047" and no text.',
  att={'scan0047.pdf': 'IMAGE-ONLY SCAN (upright). "LETTERS TESTAMENTARY - Estate of Ricardo Delgado, deceased - Executor: Maria Delgado".'},
  why='Email is identifiable only from the scan: letters testamentary for the Estate of Ricardo Delgado, so probate 1002-001 (not the closed purchase 1002-002).'),
'AAMk3b84e55160': dict(cat='matter', m='1004-001', x=['1004-002'], f=[],
  sum='Elena tells Leah the notification letter went out and tells Jonah the Heron board vote is set for September 2.',
  why='Two matters of the same client (Calloway). The item addressed first (Leah, notification letter after the access incident) belongs to the privacy investigation 1004-001, which is RESTRICTED, so the primary goes under Restricted. Stub in 1004-002 Correspondence (same client).'),
'AAMk41b53302fc': dict(cat='matter', m='1001-002', f=[],
  sum='Leah tells Dana the response to the SunHarvest office action was filed.',
  why='SunHarvest trademark (1001-002). Not the Kestrel dispute.'),
'AAMk4ad8b9b45c': dict(cat='matter', m='1001-001', f=[],
  sum="Kestrel's counsel floats a structured credit on future orders for settlement purposes (FRE 408).",
  why='Kestrel dispute (hold). Opposing counsel, so no privilege.'),
'AAMk4ba3ea284d': dict(cat='needs_review', f=['misdirected'],
  sum='Lucy Carter of Carter Whitfield LLP sends closing documents for "the Martinez closing" to Mira.',
  why='No Martinez client or matter exists in matters.csv and the sender is from an unrelated firm; clearly meant for someone else. Not read further, as the rules require. The text says documents are attached but the export has no attachment.',
  nr=('Misdirected email: Martinez closing documents from another law firm; no such client or matter at Hartwell & Osei.',
      'Whether to notify the sender and delete or return the message, and whether the confidentiality of another firm\'s documents needs handling.',
      'Mira Osei (addressee) with Carla Ruiz (office manager)')),
'AAMk4f164f1513': dict(cat='non_matter',
  sum='Personal message asking whether dinner on Friday is still on.',
  why='Personal message to Ravi from Priya Iyer (mailbox.test, personal address); no client or matter content.'),
'AAMk5376c468ae': dict(cat='matter', m='1001-003', f=[],
  sum='Dana sends the Q2 board minutes for the minute book.',
  att={'q2_minutes.pdf': 'Text PDF: "BRIGHTWATER FOODS INC. - Minutes of the Board of Directors - Q2 2026".'},
  why='Corporate/board matter (1001-003), Jonah Hartwell. Same client as the Kestrel dispute but unrelated to it, so no hold.'),
'AAMk5645100358': dict(cat='matter', m='1003-002', f=[],
  sum='Anika asks Hank to confirm the signatory for the Dock 7 renewal signature blocks.',
  why='Dock 7 lease renewal (1003-002). Anika Brandt is screened only from 1003-001 (Tran), so no wall incident: different matter of the same client.'),
'AAMk6078511608': dict(cat='matter', m='1004-001', f=[],
  sum='Elena sends a document with the subject "doc" and no text.',
  att={'doc_0828.pdf': 'IMAGE-ONLY SCAN, upside down (rotated 180). "CONFIDENTIAL - Calloway Medical Group PC - Risk assessment - July access incident".'},
  why='Only identifiable from the scan: a risk assessment of the July access incident, i.e. the privacy investigation (1004-001, RESTRICTED), not Project Heron.'),
'AAMk65fb710734': dict(cat='matter', m='1001-001', f=[],
  sum='Mira sends Dana the litigation hold notice for Kestrel, effective today.',
  att={'litigation_hold_notice.pdf': 'Text PDF: "LITIGATION HOLD NOTICE - Matter: Brightwater v. Kestrel Packaging - Effective: 2026-08-10".'},
  why='The hold start date itself (2026-08-10) counts as on or after the hold start, so flag hold applies. Tom Weller (staff) copied.'),
'AAMk684735af1c': dict(cat='matter', m='1002-001', f=[],
  sum='Maria says the court set the hearing on the estate inventory for October 6.',
  why='Estate probate (1002-001).'),
'AAMk68f6cdb2f8': dict(cat='needs_review', f=['new-matter-request'],
  sum="Maria asks whether the name 'Delgado Bakery LLC' is available for her daughter's bakery.",
  why='Follow-up to the 08-19 bakery LLC request. No bakery/LLC matter exists, and it has nothing to do with the estate or the closed purchase, so it is a new request for services outside every matter.',
  nr=('Request for LLC formation help for Maria Delgado\'s daughter (new matter, continuing request).',
      'Whether to take the engagement (client or the daughter?), run conflict checks and open a matter.',
      'Ravi Iyer (responsible for client 1002), with Jonah Hartwell on conflicts')),
'AAMk6b65bd9acb': dict(cat='matter', m='1005-001', f=[],
  sum='Paul sends a scan with subject "scan"; no text.',
  att={'statement_jul.pdf': 'IMAGE-ONLY SCAN (slightly skewed). "FIRST HARBOR BANK - Account holder: Paul Ostrander - Statement period: July 2026".'},
  why='Only the scan identifies it: Paul\'s July bank statement, responding to Ravi\'s request for bank statements for the divorce financial disclosure (1005-001).'),
'AAMk7218187993': dict(cat='matter', m='1007-001', f=[],
  sum='Sam sends the signed signature page.',
  att={'sigpage.pdf': 'IMAGE-ONLY SCAN (upright). "BLUE HERON MARINA LLC - Slip C Lease Agreement - signature page - Signed: S. Pryce, Manager".'},
  why='Subject says "Heron slip agreement"; the scan confirms the Slip C lease of Blue Heron Marina (1007-001), not Project Heron.'),
'AAMk737734d7c1': dict(cat='matter', m='1002-001', f=[],
  sum="Maria sends the appraiser's report on her father's house.",
  att={'scan_0812.pdf': 'IMAGE-ONLY SCAN, rotated 90 degrees. "APPRAISAL REPORT - Property: 88 Alder Street - Prepared for: Estate of Ricardo Delgado - Purpose: date-of-death valuation - Opinion of value: $412,000".'},
  why='Estate property 88 Alder Street (matters.csv notes) and Estate of Ricardo Delgado: probate 1002-001.'),
'AAMk73f6fa5db8': dict(cat='matter', m='1001-001', x=['1001-002'], f=[],
  sum='Dana tells Mira more April Kestrel emails were found, and tells Leah the SunHarvest packaging launch moved to November.',
  why='Two matters of the same client (Brightwater). The Kestrel item is addressed first (Mira), so primary 1001-001 (hold, dated on the hold start date); stub in 1001-002 Correspondence.'),
'AAMk79830c71c2': dict(cat='non_matter',
  sum='Marketing for an ethics CLE webinar.',
  why='Unsolicited marketing to the front desk.'),
'AAMk833acb6266': dict(cat='matter', m='1006-001', f=['potential-conflict'],
  sum='The HOA board says Maria Delgado, new owner of 14 Fenwick Lane, disputes the transfer fee and asks Leah to send a demand letter.',
  why='Client is the Fenwick Lane HOA (1006), assessment collections, so primary 1006-001 (not Delgado\'s purchase). Maria Delgado is a current client (1002), so the HOA\'s requested demand letter is adverse to another current client: potential-conflict. No stub in any Delgado folder (different client, rule 2). Overlapping name: Fenwick Lane HOA vs 14 Fenwick Lane purchase.'),
'AAMk8917362f25': dict(cat='matter', m='1006-001', f=[],
  sum='HOA board reports the unit 22 owner is four months behind on dues and attaches the ledger.',
  att={'ledger.pdf': 'IMAGE-ONLY SCAN (upright). "FENWICK LANE HOMEOWNERS ASSOCIATION - Owner ledger - Unit 22 (owner: K. Albright) - Balance due: $1,860.00".'},
  why='Assessment collections for the HOA (1006-001); the scan confirms the HOA ledger. Unit 22 owner is a third party, not a firm client.'),
'AAMk8dff666589': dict(cat='needs_review', f=['new-matter-request'],
  sum="Maria asks, 'unrelated to Dad's estate', whether Ravi can help her daughter form a bakery LLC.",
  why='New request for services outside every existing matter (stated to be unrelated to the estate).',
  nr=('New request for legal services (bakery LLC formation) from existing client Maria Delgado; no matching matter.',
      'Whether to accept the engagement, who the client is (Maria or her daughter) and whether to open a new matter.',
      'Ravi Iyer (responsible for client 1002), with Jonah Hartwell on conflicts')),
'AAMk9011fa2ac0': dict(cat='firm_admin',
  sum='Office manager asks staff to submit Q3 time entries by September 5.',
  why='Internal billing notice to all attorneys. It lists Anika Brandt but has nothing to do with any matter, so no wall incident.'),
'AAMk9012b2a414': dict(cat='matter', m='1007-001', f=[],
  sum='Sam sends a receipt, subject "Re: Heron".',
  att={'receipt.pdf': 'IMAGE-ONLY SCAN (upright). "BLUE HERON MARINA LLC - Slip C - first month\'s rent received - Receipt no. 0091".'},
  why='Subject "Heron" is ambiguous; sender domain and the scan (Slip C rent receipt) place it in the Blue Heron Marina Slip C lease (1007-001), not Project Heron.'),
'AAMk9770c6a5b8': dict(cat='duplicate', f=[],
  sum="Duplicate of AAMk32d7a94ded (Tolland's deposition notice).",
  why='Same Message-ID as AAMk32d7a94ded; the original is filed in 1001-001, which is under hold, and this copy is dated on or after the hold start, so it is retained in the matter as _dup (rule 6).'),
'AAMk980ab8ab67': dict(cat='matter', m='1001-001', f=[],
  sum="Kestrel's counsel accepts Mira's edits to paragraphs 4 and 9 of the protective order.",
  why='Brightwater v. Kestrel. Original of a duplicate pair (same Message-ID as AAMka2b1852f27). Dated 2026-08-07, before the hold start, so no hold flag. Opposing counsel, no privilege.'),
'AAMk993deffa38': dict(cat='non_matter', f=['phishing'],
  sum='"IT Support" tells three attorneys their mailbox password expires today and to verify at a link.',
  why='Sender domain is hartwe11-osei.test (digits "11" in place of "ll"), not hartwell-osei.test; it imitates the firm and urges a credential verification: phishing.'),
'AAMk9da13ffe79': dict(cat='matter', m='1004-001', f=[],
  sum="Elena sends the IT vendor's draft timeline of the July access incident; asks to keep circulation tight.",
  att={'incident_timeline_draft.pdf': 'Text PDF: "Calloway Medical Group PC - Access incident timeline (DRAFT): Jul 14 unusual login detected; Jul 15 account disabled".'},
  why='Calloway privacy investigation (1004-001), RESTRICTED.'),
'AAMk9f28518867': dict(cat='matter', m='1003-001', f=[],
  sum="Hank sends the personnel file excerpt Mira asked for.",
  att={'personnel_excerpt.pdf': 'IMAGE-ONLY SCAN (upright). "NORTHPOINT LOGISTICS LLC - PERSONNEL FILE - Employee: Jessica Tran - Performance reviews 2024-2026 (excerpt)".'},
  why='Scan names Jessica Tran, the adverse claimant in 1003-001. Anika is not on the email.'),
'AAMka2b1852f27': dict(cat='duplicate', f=[],
  sum='Duplicate of AAMk980ab8ab67 (protective order edits accepted).',
  why='Same Message-ID as AAMk980ab8ab67; dated 2026-08-07, before the hold start (2026-08-10), so the hold exception does not apply and it goes to _Duplicates.'),
'AAMka69d95847e': dict(cat='matter', m='1003-001', f=[],
  sum="Tran's counsel offers mediation dates of Sept 15 or 22 and asks for confirmation.",
  why='Tran employment claim (1003-001); opposing counsel (Cole Labor Law). Anika Brandt, screened since 2026-07-01, is copied: ethical-wall incident. Opposing counsel takes part, so no privilege.'),
'AAMka775139237': dict(cat='matter', m='1003-002', x=['1003-001'], f=[],
  sum="Hank reports the landlord accepted the Dock 7 counter, and separately asks whether Tran's lawyer may call him directly.",
  why='Two matters of the same client (Northpoint). Dock 7 is addressed first, so primary 1003-002; stub in 1003-001 Correspondence. The stub makes the email count as being about the Tran matter, and Anika Brandt (screened) is copied: ethical-wall incident.  The question from the client about contact by opposing counsel goes to Mira (action list only; not an attorney-action flag, since the hold is not involved).'),
'AAMkacc74c7ccf': dict(cat='matter', m='1003-002', f=[],
  sum='Insurer says the landlord needs an updated certificate naming it additional insured and asks the tenant\'s broker.',
  why='Dock 7 lease renewal (1003-002); third party (insurer) so no privilege. Sent to the front-desk mailbox.'),
'AAMkafd8e94b15': dict(cat='non_matter',
  sum='Law Weekly newsletter on employment law.',
  why='Newsletter. Subject mentions employment law but there is no matter content (Tran is not mentioned).'),
'AAMkb5faf8cda9': dict(cat='matter', m='1008-001', f=[],
  sum='Kenji sends a scan, subject "Scan", no text.',
  att={'scan_lien.pdf': 'IMAGE-ONLY SCAN (upright). "NOTICE OF MECHANIC\'S LIEN - Claimant: Rivera & Sons Roofing - Property: 210 Mill Street".'},
  why='Only the scan identifies it: a mechanic\'s lien by Rivera & Sons on 210 Mill Street, so 1008-001.'),
'AAMkbda7677796': dict(cat='matter', m='1001-001', f=[],
  sum='Tom proposes Bates ranges for the first production and notes draft privilege calls.',
  why='Kestrel dispute (hold), internal staff only: work product.'),
'AAMkc250b601fc': dict(cat='matter', m='1005-001', f=[],
  sum="Opposing counsel sends a proposed parenting plan.",
  att={'parenting_plan.pdf': 'IMAGE-ONLY SCAN (upright). "PROPOSED PARENTING PLAN - In re the Marriage of Ostrander - Submitted by Respondent".'},
  why='Ostrander divorce (1005-001); the scan names the Ostrander marriage. Opposing counsel, no privilege.'),
'AAMkc707b37e14': dict(cat='needs_review', f=['potential-conflict', 'new-matter-request'],
  sum='Kestrel Packaging CEO asks Jonah to engage the firm on a new distribution agreement.',
  why='Kestrel is the adverse party in Brightwater v. Kestrel (1001-001, hold). An adverse party wants to hire the firm: potential-conflict and new-matter-request. Not filed in 1001-001 (it is not about the matter and the firm has not accepted). Kestrel is represented by Tolland Law.',
  nr=('Adverse party to a current client (Kestrel) asks to engage the firm; conflict check required.',
      'Whether to decline, and how to respond to a represented adverse party (Kestrel is represented by Tolland Law in 1001-001); whether Brightwater must be told.',
      'Jonah Hartwell (ethics partner and addressee) with Mira Osei (responsible for 1001-001)')),
'AAMkc7ec99108d': dict(cat='matter', m='1001-001', f=[],
  sum="Kestrel's counsel sends a proposed stipulated protective order, edits due by the 7th.",
  att={'proposed_protective_order.pdf': 'Text PDF: "UNITED STATES DISTRICT COURT - Brightwater Foods Inc. v. Kestrel Packaging Ltd - [PROPOSED] STIPULATED PROTECTIVE ORDER".'},
  why='Brightwater v. Kestrel (1001-001); dated 2026-08-04, before hold start so no hold flag. Opposing counsel.'),
'AAMkcd2f45e678': dict(cat='matter', m='1003-001', f=[],
  sum="Anika offers to help with the Tran deposition outline because she worked on Ms. Tran's side at her old firm.",
  why='Tran matter (1003-001). Anika Brandt is screened from it since 2026-07-01 and wrote about it: ethical-wall incident (sender). Her statement about prior work on the adverse side is a separate concern for the ethics partner.'),
'AAMkd403d71684': dict(cat='matter', m='1008-001', f=[],
  sum="Rivera & Sons' accounts department says invoice 4471 (roofing, 210 Mill Street) is 60 days overdue and says it was told by Sato to copy the firm.",
  why='Rivera roofing dispute (1008-001); adverse party sender, so no privilege. Sent to the front-desk mailbox.'),
'AAMkda8201e2bd': dict(cat='matter', m='1005-001', f=[],
  sum='Ravi reminds Paul his financial disclosure is due August 28 and asks for the last three bank statements.',
  why='Ostrander divorce (1005-001).'),
'AAMkdb8f4d3e27': dict(cat='matter', m='1001-002', f=[],
  sum='Leah tells Dana of a USPTO office action on SunHarvest citing a prior registration.',
  why='SunHarvest trademark (1001-002).'),
'AAMkdd73cf256d': dict(cat='matter', m='1001-001', f=[],
  sum='Dana sends March-May delivery logs with short shipments from Kestrel highlighted.',
  att={'delivery_logs_mar-may.pdf': 'Text PDF: "Brightwater Foods Inc. - Inbound delivery log - Supplier: Kestrel Packaging Ltd - Mar-May 2026 - Short shipments flagged: 14 of 61 deliveries".'},
  why='Kestrel dispute (1001-001). Dated 2026-08-03, before the hold start, so no hold flag, but still a privileged attorney-client email in the hold matter and therefore on the privilege log.'),
'AAMke130b17d0b': dict(cat='matter', m='1004-001', f=[],
  sum='Leah sends Elena draft v2 of the regulator notification letter (privileged).',
  why='Notification to a regulator after the access incident: privacy investigation (1004-001), RESTRICTED.'),
'AAMke3cf44dd3f': dict(cat='matter', m='1002-002', f=['potential-conflict'],
  sum='Maria asks whether she owes a transfer fee demanded by the Fenwick Lane HOA from the June purchase.',
  att={'hoa_letter.pdf': 'IMAGE-ONLY SCAN, slightly skewed. "FENWICK LANE HOMEOWNERS ASSOCIATION - To: Maria Delgado, 14 Fenwick Lane - Transfer fee due on June 2026 conveyance: $750.00".'},
  why='The question is about the 14 Fenwick Lane purchase (1002-002), which closed 2026-06-30; the email is dated 2026-08-07, so post-closing. The HOA is also a current client (1006), so this shows two current clients adverse: potential-conflict. No stub in the HOA folders (different client).'),
'AAMkecc20ef164': dict(cat='matter', m='1001-001', f=['attorney-action'],
  sum="Dana asks whether Brightwater's IT can purge the April purchasing mailbox.",
  why='Kestrel dispute, under hold. The client asks for deletion of April Kestrel emails, which the hold forbids: attorney-action.'),
'AAMked35b00a54': dict(cat='matter', m='1003-002', f=[],
  sum='Hank sends a document with subject "fwd", no text.',
  att={'scan0103.pdf': 'IMAGE-ONLY SCAN, rotated 90 degrees. "LEASE AMENDMENT NO. 3 - Premises: Dock 7 - Landlord: Harborview Properties - Tenant: Northpoint Logistics LLC - EXECUTED".'},
  why='Only the scan identifies it: executed Dock 7 lease amendment, so 1003-002.'),
'AAMkeefee5a5b2': dict(cat='matter', m='1005-001', f=['delivery-failure'], priv='none',
  sum="Bounce: Ravi's 'Financial disclosure deadline' email to paul.ostrander@mailbox.test was not delivered.",
  why='Delivery failure, filed in the matter of the original email (Ostrander divorce 1005-001). Automated sender, so privilege none. Paul wrote to the firm from the same address on 08-12 and 09-01.'),
}

# attorney_actions: (person, email id, why)
ACTIONS = [
 ('Jonah Hartwell (ethics partner)', 'AAMka69d95847e', 'Wall incident: Anika Brandt (screened from 1003-001 since 2026-07-01) was copied on opposing counsel\'s Tran mediation email.'),
 ('Jonah Hartwell (ethics partner)', 'AAMkcd2f45e678', 'Wall incident: Anika Brandt wrote about the Tran deposition and says she worked on Ms. Tran\'s side at her old firm; decide whether the screen is adequate.'),
 ('Jonah Hartwell (ethics partner)', 'AAMka775139237', 'Wall incident: Anika Brandt was copied on an email that also covers the Tran matter (cross-referenced to 1003-001).'),
 ('Jonah Hartwell (ethics partner)', 'AAMkc707b37e14', 'Potential conflict: adverse party Kestrel asks to hire the firm. Needs a conflict decision and a response.'),
 ('Jonah Hartwell (ethics partner)', 'AAMk833acb6266', 'Potential conflict: the HOA (client) wants a demand letter against Maria Delgado (current client).'),
 ('Jonah Hartwell (ethics partner)', 'AAMke3cf44dd3f', 'Potential conflict: Maria Delgado (client) is in a transfer fee dispute with the HOA (current client).'),
 ('Jonah Hartwell (ethics partner)', 'AAMk090f3ebdd3', 'Potential conflict: Paul Ostrander\'s brother wants a slip contract at Blue Heron Marina (current client).'),
 ('Jonah Hartwell', 'AAMk1b66809a11', 'New-matter request: Blue Heron Marina fuel dock damage claim. Open a matter or decline; run a conflict check.'),
 ('Jonah Hartwell', 'AAMk090f3ebdd3', 'New-matter request touching Blue Heron Marina (your client) from Paul Ostrander\'s brother.'),
 ('Mira Osei', 'AAMka775139237', 'Hank asks whether Tran\'s lawyer may contact him directly. Answer him (Tran matter 1003-001).'),
 ('Mira Osei', 'AAMkecc20ef164', 'Request that conflicts with the litigation hold: client wants to purge the April mailbox. Tell Dana in writing not to delete anything.'),
 ('Mira Osei', 'AAMkc707b37e14', 'Kestrel (adverse in 1001-001) is asking to engage the firm; coordinate with Jonah.'),
 ('Mira Osei', 'AAMkcd2f45e678', 'Anika wrote offering help on the Tran deposition; you are the addressee. Reply consistent with the screen and tell Jonah.'),
 ('Mira Osei', 'AAMk4ba3ea284d', 'Misdirected email from Carter Whitfield LLP (Martinez closing). Do not use it; tell the sender.'),
 ('Mira Osei', 'AAMk32d7a94ded', 'Kestrel counsel wants dates for Dana Whitcomb\'s deposition in late September (duplicate copy retained under hold).'),
 ('Leah Park', 'AAMk833acb6266', 'HOA asks for a demand letter against Maria Delgado, a current client. Do not send until Jonah clears the conflict.'),
 ('Ravi Iyer', 'AAMke3cf44dd3f', 'Post-closing: Maria Delgado asks about the transfer fee on the closed purchase of 14 Fenwick Lane (closed 2026-06-30). Decide whether to reopen the matter; also a conflict (see Jonah).'),
 ('Ravi Iyer', 'AAMk8dff666589', 'New-matter request: Maria Delgado\'s daughter\'s bakery LLC.'),
 ('Ravi Iyer', 'AAMk68f6cdb2f8', 'Follow-up on the bakery LLC request (name availability).'),
 ('Ravi Iyer', 'AAMk090f3ebdd3', 'Paul Ostrander asks whether you can help his brother with a Blue Heron Marina slip contract; do not accept before the conflict check.'),
 ('Ravi Iyer', 'AAMkeefee5a5b2', 'Delivery failure: the financial disclosure reminder to Paul Ostrander bounced. Re-send it by another route and check the address.'),
 ('IT (via Carla Ruiz, office manager)', 'AAMk993deffa38', 'Phishing from the look-alike domain hartwe11-osei.test sent to Mira, Leah and Ravi. Block the domain, check whether anyone clicked, and warn staff.'),
]
